/*
 * FolderDiffGUI.java
 *
 * Created on November 5, 2008, 5:21 PM
 */
package gui;

import com.folderdiff.DiffEngine;
import com.folderdiff.DiffFile;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author  satyam
 */
public class FolderDiffGUI extends javax.swing.JFrame {

    /** Creates new form FolderDiffGUI */
    public FolderDiffGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root1Field = new javax.swing.JTextField();
        root1Label = new javax.swing.JLabel();
        doDiffButton = new javax.swing.JButton();
        root2Label = new javax.swing.JLabel();
        root2Field = new javax.swing.JTextField();
        chooseRoot1Button = new javax.swing.JButton();
        chooseRoot2Button = new javax.swing.JButton();
        resultMsgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Folder Diff"); // NOI18N

        root1Field.setEditable(false);

        root1Label.setText("Root1:");

        doDiffButton.setText("Do Diff");
        doDiffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doDiffButtonActionPerformed(evt);
            }
        });

        root2Label.setText("Root2:");

        root2Field.setEditable(false);

        chooseRoot1Button.setText("Browse");
        chooseRoot1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRoot1ButtonActionPerformed(evt);
            }
        });

        chooseRoot2Button.setText("Browse");
        chooseRoot2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRoot2ButtonActionPerformed(evt);
            }
        });

        resultMsgLabel.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(resultMsgLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doDiffButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(root1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(root1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseRoot1Button)
                                .addGap(26, 26, 26)
                                .addComponent(root2Label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(root2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseRoot2Button)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chooseRoot1Button, chooseRoot2Button, doDiffButton, root1Field, root2Field});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(root1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(root2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(root1Label)
                    .addComponent(root2Label)
                    .addComponent(chooseRoot1Button)
                    .addComponent(chooseRoot2Button))
                .addGap(32, 32, 32)
                .addComponent(doDiffButton)
                .addGap(38, 38, 38)
                .addComponent(resultMsgLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void doDiffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doDiffButtonActionPerformed
    List<DiffFile> list = DiffEngine.doDiff(new String[]{root1Field.getText(), root2Field.getText()});
    File html = DiffEngine.writeToHtml(list, new String[]{root1Field.getText(), root2Field.getText()});    
    BrowserControl.displayURL(html.toString());
    //html.delete();
}//GEN-LAST:event_doDiffButtonActionPerformed

private void chooseRoot1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRoot1ButtonActionPerformed
    final JFileChooser fc = new JFileChooser();
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = fc.showOpenDialog(rootPane);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        root1Field.setText(file.toString()+file.separator);
    }
}//GEN-LAST:event_chooseRoot1ButtonActionPerformed

private void chooseRoot2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRoot2ButtonActionPerformed
    final JFileChooser fc = new JFileChooser();
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = fc.showOpenDialog(rootPane);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        root2Field.setText(file.toString()+file.separator);
    }
}//GEN-LAST:event_chooseRoot2ButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolderDiffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseRoot1Button;
    private javax.swing.JButton chooseRoot2Button;
    private javax.swing.JButton doDiffButton;
    private javax.swing.JLabel resultMsgLabel;
    private javax.swing.JTextField root1Field;
    private javax.swing.JLabel root1Label;
    private javax.swing.JTextField root2Field;
    private javax.swing.JLabel root2Label;
    // End of variables declaration//GEN-END:variables

}
